get_filename_component(CMAKE_DIR "${CMAKE_CURRENT_LIST_FILE}" PATH)

if ((NOT(DEFINED DEFAULT_PLATFORM)) AND (NOT(DEFINED MAKE_ARM)))
    set(PLATFORM x86)
elseif((DEFINED DEFAULT_PLATFORM STREQUAL "aarch64") OR (MAKE_ARM STREQUAL "true"))
    set(PLATFORM arm)
else()
    set(PLATFORM x86)
endif()

file(GLOB CEMLOG_LIBS ${CMAKE_DIR}/../lib/${PLATFORM}/libcemlog.so)
set(CEM_LOG_LIB_DIRS ${CMAKE_DIR}/../lib/${PLATFORM})
set(CEMLOG_INCLUDE_DIRS ${CMAKE_DIR}/../include/cem_log)

set(CEM_LIBS ${CEM_LIBS} ${CEMLOG_LIBS})
set(CEM_INCLUDE_DIRS ${CEM_INCLUDE_DIRS} ${CEMLOG_INCLUDE_DIRS})